In [1]:
import numpy as np

# Program 1
Generate a 3x4 NumPy array with random integers between 1 and 50.

In [2]:
arr = np.random.randint(1, 50, (3, 4))
arr

array([[23,  1, 28, 16],
       [37, 13, 33, 22],
       [24, 24,  6, 45]], dtype=int32)

Calculate and print the mean, median, and standard deviation of the array.

In [3]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

22.666666666666668
23.5
12.002314591592555


Print the sum of all elements and the sum of each row.

In [4]:
print(np.sum(arr))
print(np.sum(arr, axis=0))

272
[84 38 67 83]


Reshape the 3x4 array into a 2x6 array and print it.

In [5]:
print(np.reshape(arr, (2, 6)))

[[23  1 28 16 37 13]
 [33 22 24 24  6 45]]


# Program 2
Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations.

In [6]:
x = np.random.randint(1, 100, (3, 3))
y = np.random.randint(1, 100, (3, 3))
print(x)
print()
print(y)

[[28 94 41]
 [62 79 47]
 [95 85 52]]

[[85 79 30]
 [94 72 93]
 [71  2 57]]


Matrix addition

In [7]:
print(x + y)

[[113 173  71]
 [156 151 140]
 [166  87 109]]


Matrix subtraction

In [8]:
print(x - y)

[[-57  15  11]
 [-32   7 -46]
 [ 24  83  -5]]


Matrix multiplication (element-wise and dot product)

In [9]:
print(x @ y)

[[14127  9062 11919]
 [16033 10680 11886]
 [19757 13729 13719]]


Transpose of a matrix

In [10]:
print(x.T)
print()
print(y.T)

[[28 62 95]
 [94 79 85]
 [41 47 52]]

[[85 94 71]
 [79 72  2]
 [30 93 57]]


Determinant and inverse (if applicable)

In [11]:
print(np.linalg.det(x))
print()
print(np.linalg.det(y))
print()
print(np.linalg.inv(x))
print()
print(np.linalg.inv(y))

28182.999999999993

283664.9999999997

[[ 0.00400951 -0.04978178  0.04183373]
 [ 0.04403364 -0.08654153  0.0435014 ]
 [-0.07930313  0.23240961 -0.1283043 ]]

[[ 0.01381207 -0.01566284  0.01828565]
 [ 0.00438898  0.00957115 -0.01792607]
 [-0.0173585   0.01917403 -0.00460402]]
